### ISSUE TITLE
link to website / info page

### ISSUE THREAD

**Issue by lpoujade** [lpoujade/unicon20_app#45]
add an item in tab bar opening a link to the wordpress, or showing articles content from wordpress info pages

**Comment by sguesdon** [comment]
can you give more information about the expected ?

**Comment by lpoujade** [comment]
yep of course ! The thing is, on unicon20.fr wordpress there are thow type of articles:
- news ([here](https://www.unicon20.fr/news/))
- and info pages, like [this one](https://www.unicon20.fr/practical-informations/traveling-to-grenoble/) 

News are quick infos like a feed, eventually outdated; but pages are 'static' and are always updated to reflect last changes

We already get the news in the app via the wordpress API, but it could be great if app users can quickly access to other informations. [There are endpoints](https://unicon20.fr/wp-json/wp/v2/pages) for the pages in the wp api similar to those for the news, but we need a different presentation

What could be great is to have an informations tab showing a big card for each [page category](https://unicon20.fr/wp-json/wp/v2/tags), and then the list of pages in this category when the user click on a card. As we will probably not be able to show the exact page (i'm thinking about embeded widget/iframe/wordpress plugin/etc), I think the best way is to open the device browser when an user wants to access to a page. Maybe somes users would like to access to those pages while being offline, so showing the page text only when there is no internet connection could be great too, but ideally all informations needed during the event (places, schedules, startlists, results etc) should be directly available in the app

Also, I want to keep the app usable with others wordpress hosts (and other ics sources) so we'll not hardcode pages or categories links

**Comment by lpoujade** [comment]
so indeed, pages doesn't have tags/categories; we can make a screen with cards a list of pages
